name: Auto Assign yml updater
on:
  pull_request:
    types: [opened reopened]
jobs:
  yamlupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: before
      run: cat .github/auto_assign.yml
    - name: AutoBotYamlFileUpdater
      uses: SFLScientific/AutoBotYaml@master
      with:
        token: ${{ secrets.SFLOrgReadAccessToken }}
    - name: after
      run: cat .github/auto_assign.yml
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Updated auto_assign.yml"
        add: ".github/auto_assign.yml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
